// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJpvV3EuvGqPqNeG6ghZA4Vx6J2EWaagc',
    appId: '1:584487782784:web:b33252e52ce59a85201965',
    messagingSenderId: '584487782784',
    projectId: 'pomoflowchat',
    authDomain: 'pomoflowchat.firebaseapp.com',
    storageBucket: 'pomoflowchat.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAReiTodQuHhxefCO32h9KZ2t4qNs15J2U',
    appId: '1:584487782784:android:66617b4adf708e47201965',
    messagingSenderId: '584487782784',
    projectId: 'pomoflowchat',
    storageBucket: 'pomoflowchat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcJU83FUJ-QGtEDMxpk86W5Kl4yQBGuqk',
    appId: '1:584487782784:ios:3d844b92e6785238201965',
    messagingSenderId: '584487782784',
    projectId: 'pomoflowchat',
    storageBucket: 'pomoflowchat.firebasestorage.app',
    iosBundleId: 'com.example.pomoflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcJU83FUJ-QGtEDMxpk86W5Kl4yQBGuqk',
    appId: '1:584487782784:ios:3d844b92e6785238201965',
    messagingSenderId: '584487782784',
    projectId: 'pomoflowchat',
    storageBucket: 'pomoflowchat.firebasestorage.app',
    iosBundleId: 'com.example.pomoflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJpvV3EuvGqPqNeG6ghZA4Vx6J2EWaagc',
    appId: '1:584487782784:web:79d250a587190f98201965',
    messagingSenderId: '584487782784',
    projectId: 'pomoflowchat',
    authDomain: 'pomoflowchat.firebaseapp.com',
    storageBucket: 'pomoflowchat.firebasestorage.app',
  );

}